name: 'Deploy para VPS'

on:
  push:
    branches:
      - main

jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 'Baixar o código'
        uses: actions/checkout@v4

      - name: 'Copiar arquivos para VPS'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 'host'
          username: 'ubuntu'
          key: ''
          source: '.'
          target: '/testegit'
