name: 'Deploy para VPS'

on:
  push:
    branches:
      - main

jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 'Baixar o código'
        uses: actions/checkout@v4

      - name: 'Criar diretório no VPS'
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p /testgit  # Cria a pasta se não existir

      - name: 'Copiar arquivos para VPS'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: '.'
          target: '/testgit'

      # Descomente e ajuste os passos conforme necessário
      # - name: 'build da aplicação'
      #   uses: appleboy/ssh-action@v1.1.0
      #   with:
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.USERNAME }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     script: |
      #       cd /testgit
      #       composer install --no-dev --no-progress -a
      #       php artisan optimize
      #       chown -R ubuntu:ubuntu .
