name: 'Deploy para VPS'

on:
  push:
    branches:
      - main

jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 'Baixar o código'
        uses: actions/checkout@v4

      - name: 'Copiar arquivos para VPS'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: '164.152.32.246'
          username: 'ubuntu'
          key: -----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEA4hCSmydK+iJYjPJPJKSqowDZaQYE7SH61DRJPBKr7VD5up9C
WZlzOVqhySc/69hSh7eLi66kTLOCwVj+zuYdBOUonjqp3nHpyZJJUyZ6xYmAnySt
Y9k3Dvamx9C42e5nbCce6RQrONc2Aqiol1fd3tfvD0LyrcPCoFqHNcJrwNl+pRiK
bF9Z8dyUQEjGuIp37XTtDo/qkHoD3xequSV5DeeHUmQSleni0fi+j2ER7mCZOCWG
vMGwc+KQmoRFxIzVSViBxflquS1F9pxdCAkmg19RouJfsQCBt01Y9kv9JDLJ1ze7
1DKrOqijN+F9XmdJWKzsR1FWPH2dasYeGnB+TwIDAQABAoIBAB/oOukPOLPpWRo7
sRP48eSj4AvEv7lAjIibAKMr93w9a6H9jH3c/LhhpGgh1BHTrIJfU6DZe3Mf+xqT
FxPYwsvIFF2Q5hzxcw/yR8smqTlsWO0dXiOzquO/yHZ3bT/FOG+5bdFz+U3CgmsJ
pxIFYtlrHODIkDwaX0QGwwLBeDf1ts3MOSw6hjsITchS3T4npAie3PjTLOqPRTqM
JdzeINMulPxv4wajyN5brt8MXLOMYICC4o9YELh5TzgdLsabbEV7LMAPPEPRvbLf
hsCdXWjMlXPGtgvH7JzWW0sUXLLhQxfF94RSi84jq8oYoON7+uB2jW63S35n8c0p
UDsGXrECgYEA9trMw1AIW/dtnBzdB8EE4rzIg7XIWojO9SgUrf3c3I2TY85PnygO
FjVit1OBz11NJuOFX/LLLeeciKxIH3xFPS22WrtSmKrbk9Hmkb2iwHEXBpnBe35K
PD1szP4j65iZJ1nMlQmOUTRp98EwNkxhesMk+c2sCAD03C6usJHxQFsCgYEA6nCZ
L/0vdWIlqVskTKNdAUi5+97WII9GGjummC93ZEiNCQegOljp0RdXD0uAnbucfsKS
Adz8ip1D/dE4QBT2pWwvWO8yoQpxwfT2nvNGEqcC/HtsrB0SCHUzZ3P8reDlzIc9
5M4ERaLZKEmRz5BPeDlGsNlF0ZbvUKzBihXK3B0CgYBzodxm5Rd1VPrANPkIh87t
EvduUvmuBwXC6up88jzCB4NyLhM3/4BRwOIj8/cLlq3sOImif03Ti/nUP7dtID4i
wUX5TGQNZYODw8AYptcVBCSAEAgE/Ax0GWXcxHM5Cfs75qGhcp96xG2bA6C83pyO
79hjN4eNHD2W4jssNMDonwKBgQCMbkBEr7uy68S1iqPWyHCYqVDG3/eR72DFq/+h
36T7zD23L/s5mDMPDZUX01lKoqwefjxpo08fVQ76Rk4UjLol4wUFl9rS/megEDV+
hyjtWV9/kAtLmepIaLQO/zpXiYT9m/FmUkXa1K6R5GfUVpRT5rNCkhOxdWELCUCx
j1ZBvQKBgQDGnigEGSzE6PTzPVI5tX5LlqklkKfjx0m44++kB6RWz3t54b8DOIBT
WeS1rokkPVNRtHz7d9HxwQhdl5311Bialtuvvg22Xk58MAiDG+CYnyMQr9gP/IWH
D/AJLI0yUjal8D4EoToI2YqqADgk8JtXaTlOrB/AuJOb8HJQ2mC02g==
-----END RSA PRIVATE KEY-----

          source: '.'
          target: '/testegit'

      - name: 'build da aplicaçao'
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: '164.152.32.246'
          username: 'ubuntu'
          key: -----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEA4hCSmydK+iJYjPJPJKSqowDZaQYE7SH61DRJPBKr7VD5up9C
WZlzOVqhySc/69hSh7eLi66kTLOCwVj+zuYdBOUonjqp3nHpyZJJUyZ6xYmAnySt
Y9k3Dvamx9C42e5nbCce6RQrONc2Aqiol1fd3tfvD0LyrcPCoFqHNcJrwNl+pRiK
bF9Z8dyUQEjGuIp37XTtDo/qkHoD3xequSV5DeeHUmQSleni0fi+j2ER7mCZOCWG
vMGwc+KQmoRFxIzVSViBxflquS1F9pxdCAkmg19RouJfsQCBt01Y9kv9JDLJ1ze7
1DKrOqijN+F9XmdJWKzsR1FWPH2dasYeGnB+TwIDAQABAoIBAB/oOukPOLPpWRo7
sRP48eSj4AvEv7lAjIibAKMr93w9a6H9jH3c/LhhpGgh1BHTrIJfU6DZe3Mf+xqT
FxPYwsvIFF2Q5hzxcw/yR8smqTlsWO0dXiOzquO/yHZ3bT/FOG+5bdFz+U3CgmsJ
pxIFYtlrHODIkDwaX0QGwwLBeDf1ts3MOSw6hjsITchS3T4npAie3PjTLOqPRTqM
JdzeINMulPxv4wajyN5brt8MXLOMYICC4o9YELh5TzgdLsabbEV7LMAPPEPRvbLf
hsCdXWjMlXPGtgvH7JzWW0sUXLLhQxfF94RSi84jq8oYoON7+uB2jW63S35n8c0p
UDsGXrECgYEA9trMw1AIW/dtnBzdB8EE4rzIg7XIWojO9SgUrf3c3I2TY85PnygO
FjVit1OBz11NJuOFX/LLLeeciKxIH3xFPS22WrtSmKrbk9Hmkb2iwHEXBpnBe35K
PD1szP4j65iZJ1nMlQmOUTRp98EwNkxhesMk+c2sCAD03C6usJHxQFsCgYEA6nCZ
L/0vdWIlqVskTKNdAUi5+97WII9GGjummC93ZEiNCQegOljp0RdXD0uAnbucfsKS
Adz8ip1D/dE4QBT2pWwvWO8yoQpxwfT2nvNGEqcC/HtsrB0SCHUzZ3P8reDlzIc9
5M4ERaLZKEmRz5BPeDlGsNlF0ZbvUKzBihXK3B0CgYBzodxm5Rd1VPrANPkIh87t
EvduUvmuBwXC6up88jzCB4NyLhM3/4BRwOIj8/cLlq3sOImif03Ti/nUP7dtID4i
wUX5TGQNZYODw8AYptcVBCSAEAgE/Ax0GWXcxHM5Cfs75qGhcp96xG2bA6C83pyO
79hjN4eNHD2W4jssNMDonwKBgQCMbkBEr7uy68S1iqPWyHCYqVDG3/eR72DFq/+h
36T7zD23L/s5mDMPDZUX01lKoqwefjxpo08fVQ76Rk4UjLol4wUFl9rS/megEDV+
hyjtWV9/kAtLmepIaLQO/zpXiYT9m/FmUkXa1K6R5GfUVpRT5rNCkhOxdWELCUCx
j1ZBvQKBgQDGnigEGSzE6PTzPVI5tX5LlqklkKfjx0m44++kB6RWz3t54b8DOIBT
WeS1rokkPVNRtHz7d9HxwQhdl5311Bialtuvvg22Xk58MAiDG+CYnyMQr9gP/IWH
D/AJLI0yUjal8D4EoToI2YqqADgk8JtXaTlOrB/AuJOb8HJQ2mC02g==
-----END RSA PRIVATE KEY-----

          script: |
            cd /testgit
            composer install --no-dev --no-progress -a
            php artisan optimize
            chown -R ubuntu:ubuntu .
