# name: 'Deploy para VPS'

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build_deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: 'Baixar o código'
#         uses: actions/checkout@v4

#       - name: 'Preparar o servidor'
#         uses: appleboy/ssh-action@v1.1.0
#         with:
#           host: '${{ secrets.HOST }}'
#           username: '${{ secrets.USERNAME }}'
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           script: |
#             # Atualizar e instalar pacotes
#             sudo apt-get update
#             sudo apt-get install -y nginx python3-venv python3-pip python3-dev

#             # Configurar Nginx
#             if [ -f /etc/nginx/sites-available/default ]; then
#               sudo mv /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak
#             fi
#             echo 'server {
#                 listen 80;
#                 server_name ${HOST};
#                 location / {
#                     proxy_pass http://127.0.0.1:8000;
#                     proxy_set_header Host $host;
#                     proxy_set_header X-Real-IP $remote_addr;
#                     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#                     proxy_set_header X-Forwarded-Proto $scheme;
#                 }
#             }' | sudo tee /etc/nginx/sites-available/meuprojeto
#             sudo ln -s /etc/nginx/sites-available/meuprojeto /etc/nginx/sites-enabled/
#             sudo systemctl restart nginx

#       - name: 'Copiar arquivos para VPS'
#         uses: appleboy/scp-action@v0.1.7
#         with:
#           host: '${{ secrets.HOST }}'
#           username: '${{ secrets.USERNAME }}'
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           source: '.'
#           target: '/home/ubuntu/testegit'
#           debug: true

#       - name: 'Instalar dependências e configurar Django'
#         uses: appleboy/ssh-action@v1.1.0
#         with:
#           host: '${{ secrets.HOST }}'
#           username: '${{ secrets.USERNAME }}'
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           script: |
#             cd /home/ubuntu/testegit
#             python3 -m venv venv
#             source venv/bin/activate
#             pip install -r requirements.txt
#             python3 manage.py migrate
#             python3 manage.py collectstatic --noinput
#             chown -R ubuntu:ubuntu .
#             sudo systemctl daemon-reload
#             sudo systemctl start gunicorn
#             sudo systemctl enable gunicorn
