name: 'Deploy para VPS'

on:
  push:
    branches:
      - main

jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 'Baixar o código'
        uses: actions/checkout@v4

      - name: 'Copiar arquivos para VPS'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 'host'
          username: 'ubuntu'
          key: 'sh_private_key'
          source: '.'
          target: '/testegit'

      - name: 'build da aplicaçao'
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: 'host'
          username: 'ubuntu'
          key: 'sh_private_key'

          script: |
            cd /testgit
            composer install --no-dev --no-progress -a
            php artisan optimize
            chown -R ubuntu:ubuntu .
