name: 'Deploy para VPS'

on:
  push:
    branches:
      - main

jobs:
  simple_test:
    runs-on: ubuntu-latest

    steps:
      - name: 'Baixar o código'
        uses: actions/checkout@v4

      - name: 'Criar arquivo no servidor'
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: '${{ secrets.HOST }}'
          username: '${{ secrets.USERNAME }}'
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            touch ~/arquivo_de_teste22.txt
            ls -l ~/
          debug: true
